### ISSUE TITLE
Metadata on rOpenSci packages & data providers

### ISSUE THREAD

**Issue by cboettig** [ropensci/software-review-meta#3]
Hey @noamross , 

Somewhat along the lines of #2, been meaning to talk to you about a few metadata exercises we're trying to get a better handle on the packages in the rOpenSci suite and the data they provide.

Ultimately, the vision is that each package would include a `codemeta.json` metadata file (can largely be generated automatically, you've seen https://github.com/codemeta/codemetar which I hope to onboard itself in the near future), which could in principle be a place we record information relative to onboarding as well, and what we're calling `datasauce` https://github.com/ropenscilabs/datasauce, which is a similarly lightweight JSON description of the data itself ([example](https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fgithub.com%2Fcboettig%2Fmovebank%2Fraw%2Fmaster%2Finst%2Fextdata%2Fdatasauce.json)).  

The obvious use case here is that we would just pull all these records into a single file that could be read by the rOpenSci website to populate up-to-date tables and maybe a search query system for our packages and data that they provide.  Could serve other purposes too.  We may have to tweak the metadata models to our use cases as we go along, but I think Google/Schema.org types for `SoftwareSourceCode` and `Dataset` provide good standardized and extensible starting points for us with a minimum of complexity.  

So, curious for your feedback on these metadata in general, and how we might work them into the review process.  (While datasauce isn't relevant to every package, it really would be super useful to have some kind of standard record of what APIs / Databases / types of data we have access to, with so many packages browsing the lists is no longer scaling).

**Comment by noamross** [comment]
This makes sense to me in general.  Basically, we would want to say that having a `codemeta.json` for a repo, is a best practice that we recommend, and ultimately move it to a requirement.  For recommendation, we would want to make sure that tooling and documentation/tutorials was in a good state, and to move to the required column we would want at least a good set of use cases for adoption.  So, in approximate order, I'd say we should:

1) Onboard **codemetar**
2) Promote use through blog posts and use-cases
3) Recommend usage in RO packages
3) Make a project of using **codemetar** for internal/already onboarded packages
4) Add thin wrappers in an RO helper package if needed to generate JSON-LD that includes a field for the package being peer-reivewed by ROpenSci
5) If there is adoption, require usage in RO packages

This would follow a similar pattern for **datasauce** for data in packages.  It might be interesting to speak with the group involved in this project at the last unconf: https://github.com/ropenscilabs/data-packages

I know @sckott has an rOpenSci API and we may improve it and use it for an active package dashboard instead of our current packages page (https://github.com/orgs/ropensci/projects/1), so this would be a clear use case.  @karthik Also just made a badging API that includes RO review status that might be a field specific for RO JSON.

**Comment by cboettig** [comment]
Thanks @noamross , these are great suggestions all around and super helpful.  

- Right, @sckott maintains a json manifest for all packages in [roregistry](https://github.com/ropensci/roregistry) that is parsed by [ropkgs](https://github.com/ropensci/ropkgs).  The aggregated codemeta.json file from all the individual repos would replace the currently manual maintenance of the `roregistry` manifeste.

- For current / internal packages, we're hoping to pull in some rOpenSci interns from Berkeley to help create all those `codemeta` and `datasauce` records.  Like you say, we should do that prior to requiring it for onboarding, as it will no doubt help get out the kinks in the system, though we can recommend it.  

- Right, a Hugo or Jekyll website could easily parse the json manifest to generate the site, currently that's yet another manual update.  So this would automate both the updating of the website and the updating of the manifest itself.  

- Thanks for the reminder about the data-packages listing, that's great.  I've opened an issue for that too: https://github.com/ropenscilabs/datasauce/issues/3

- should definitely figure out how to plug in between badging API and codemeta record too.

**Comment by maelle** [comment]
For the record, using Codemeta for the registry is independent of having a codemeta.json in each repo, since for the registry the plan is to re-generate codemeta.json from each repository instead of using one that'd already be in the repository (and potentially out of date).

Regarding adding review metadata to codemeta.json, see https://github.com/ropensci/codemetar/issues/23

**Comment by maelle** [comment]
datasauce has been archived
