### ISSUE TITLE
officially allow '=' and '<-'

### ISSUE THREAD

**Issue by rmflight** [ropensci/software-review-meta#71]
In a recent review that I looked over, I saw someone recommend switching their code from `=` to `<-`, given it is the official rec in the r-pkg section on code, and the most commonly used.

However, since v 3.0 at least (and probably earlier), `=` is almost equivalent to `<-`, and rarely causes problems. I have recently switched to `=` personally, b/c it is just easier to type, and does not cause me any problems in R6 objects (function declarations in R6 **have** to use `=`, or you will get an un-named entry).

It seems silly to recommend to someone that they switch their :package: from `=` to `<-` when it will not functionally make a difference.

**Comment by Robinlovelace** [comment]
Great to see this debate happening. FWIW there is a test case entering the review [process](https://github.com/ropensci/software-review/issues/266) now in the form of the [`stats19`](https://github.com/ITSLeeds/stats19) package. It uses `=` rather than `<-`. 

`=` has become the default style that I use. I used to default to `<-` (someone I was teaching told me that they switched to `<-` because of my teaching ~4 years ago!) and happily use whatever style projects I'm working on use. 

Like @rmflight I have gradually shifted to `=` for various reasons, most of which are outlined above and in the issue in the Geocomputation with R repo linked-to by @sckott above (who alerted me to this thread, thanks!). It's now relatively easy to switch [one way](https://github.com/r-lib/styler/blob/master/R/style-guides.R#L55) (or the other pending a `yihui_style()`) using the **styler** package which is great IMO. 

Should that switch be enforced though, as indicated in https://github.com/ITSLeeds/stats19/issues/24 ?

My 10 cents is that the -s of enforcing `<-` could outweigh the +s (which I think are well summarised by the **goodpractice** statement `'<-' is the standard, and R users and developers are used it and it is easier to read your code for them if you use '<-'.`). Diversity can have some benefits. But I'm also keen to hear the other side of the argument and am definitely not an `=` hard-liner (or should that be "hard double-liner" :stuck_out_tongue_winking_eye: ): running `styler::tidyverse_style()` on one's code is a probably a price worth paying for the massive benefit of the fantastic code peer review process and supportive learning community rOpenSci offers!

**Comment by yihui** [comment]
My 2 cents: whoever currently maintains the package decides whether to use `=` or `<-` (if the maintainer has a strong preference). Future maintainers are free to change it.

**Comment by sckott** [comment]
thanks for your comments @Robinlovelace and @yihui 

I think our most important consideration is consistency within a package. 

I don't have a strong preference for one or the other

**Comment by rmflight** [comment]
@sckott I agree, consistency would be key, and as a :package: reviewer I would ask for consistency if I saw both operators being used in a :package: (horrible admission, I currently have a dev :package: of my own that has both assignment operators in it :scream: ), and if I submitted that to ropensci I would fully expect to be encouraged to pick an operator and stick with it.

*But, that's not what is stated in the guidelines*. The package review guidelines currently point to a documented style that supports `<-` over `=`, *and* I've seen at least one review where that was pointed to as *why* the :package: author should change their assignment operator.

Hence my bringing up the issue here.

**Comment by noamross** [comment]
As long as we have clear guidance that prevents this topic from being debated in review threads, I'm fine with any result.  I do note that if we make a change to the guidelines, we also want to make sure that we have guidance for use and maybe custom **goodpractice**/**lintr** settings that reflect this. The default settings for these may disagree with our guidance, and it is going to cause some confusion.

**Comment by sckott** [comment]
Okay, i propose we change guidelines to 

- use either `=` or `<-`
- be consistent within a package

agreed, need to have some custom goodpractice for this

**Comment by iqis** [comment]
Wherever `=` may be misinterpreted when used in a code block inside function call, such as suppressWarnings(), one could easily wrap the code block with `{}` brackets. 

Bottom line, whether `=` or `<-`, it makes zero difference for the user.

**Comment by maelle** [comment]
Regarding the custom lintr/goodpractice setting mentioned by @noamross, I've been looking around a bit.

I'm thinking the best way would be for package authors to add a custom linter to their .lintr, something like

```r
eq_linter <- function (source_file) 
{
  lapply(ids_with_token(source_file, "LEFT_ASSIGN"), function(id) {
    parsed <- with_id(source_file, id)
    Lint(filename = source_file$filename, line_number = parsed$line1, 
         column_number = parsed$col1, type = "style", message = "Use =, not <-, for assignment.", 
         line = source_file$lines[as.character(parsed$line1)], 
         linter = "assignment_linter")
  })
}
with_defaults(assignment_linter = eq_linter)

```

But I'll have to check it works, since I saw this open `goodpractice` issue https://github.com/MangoTheCat/goodpractice/issues/117

**Comment by sckott** [comment]
thanks @maelle - where does the .lintr file go?

**Comment by maelle** [comment]
At the root.

I can't figure out how to make one with such a custom check though so I've asked in the lintr repo.

**Comment by noamross** [comment]
I disagree that the best approach would be for authors to set a custom lintr. I think it would make much more sense for us to have a wrapper around `goodpractice::gp()` for editors and reviewers to use, e.g., `rochecks::gp()`.   The check should count the number of `=` and `<-` assignments and report them, and comment that assignments should be consistent.

An associated helper function could then just run `lint_package()` looking only for assignment operators of either, so that it's easy to look them up.

**Comment by maelle** [comment]
In that case, the .lintr file could be a solution in the meantime, until we create that package. :smile_cat:

**Comment by maelle** [comment]
I understand we might not use the custom .lintr (because of Noam's comment above, and because `goodpractice` does not seem to pick it up anyway) but here's how to create one that is picked up by `lintr::lint_package()`.

1) Create the custom linter in a separate .R file, and do not forget to `usethis::use_build_ignore()` it.

```r
eq_linter <- function (source_file){
  lapply(lintr:::ids_with_token(source_file, "LEFT_ASSIGN"), function(id) {
    parsed <- lintr:::with_id(source_file, id)
    lintr::Lint(filename = source_file$filename, line_number = parsed$line1,
         column_number = parsed$col1, type = "style", message = "Use =, not <-, for assignment.",
         line = source_file$lines[as.character(parsed$line1)],
         linter = "assignment_linter")
  })
}

``` 

2) Create the .lintr

```
linters: source("eq_assignment.R"); with_defaults(assignment_linter = eq_linter)

```
The linter definition has to live in a separate R file because the .lintr is DCF.

**Comment by maelle** [comment]
Guidance updated https://ropensci.github.io/dev_guide/building.html#code-style

Keeping this issue open because we still need a tool for automatic checks.

**Comment by gaborcsardi** [comment]
Strictly speaking R6 as an example is irrelevant here, because those `=` signs are actually not assignments, but named arguments.

**Comment by maelle** [comment]
(covered by @mpadge's work in pkgreport :tada: )
