### ISSUE TITLE
task views

### ISSUE THREAD

**Issue by maelle** [ropensci/software-review-meta#80]
The dev guide states that [packages in our suite are listed in our task views](https://ropensci.github.io/dev_guide/softwarereviewintro.html#whysubmit).

Are the task views still maintained? For some of them, it does seem so. https://github.com/search?utf8=%E2%9C%93&q=user%3Aropensci+%22task+view%22&type=Repositories&ref=searchresults

What should happen?

- Removing that mention from the dev guide
- Recruiting new maintainers for the task views, and adding the task view mention to the approval comment template (at the moment it is only in https://devdevguide.netlify.com/editorguide.html#package-promotion)?

**Comment by sckott** [comment]
more or less maintained. open data and maptools are not on cran though. the latter because of political reasons we can get into at some point, not sure if open data maintainer wants to get it there or not. 

yeah, should remove mention that any particular pkg will be in our task views. 

good idea to try to get maintainers for not actively maintainted task views
